"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
scan_timeout = 100

format = """
[](fg:#8a56dc)\
$username\
[](fg:#8a56dc bg:#7449b8)\
$hostname\
[](fg:#7449b8 bg:#5e3d94)\
$os\
[](fg:#5e3d94 bg:#483170)\
$directory\
[](fg:#483170 bg:#32254c)\
$git_branch\
$git_status\
[](fg:#32254c)\
$fill\
$cmd_duration\
$python\
$nodejs\
$rust\
$golang\
$lua\
$line_break\
$character"""

[username]
show_always = true
style_user = "bg:#8a56dc fg:#010204 bold"
format = "[ $user ]($style)"

[hostname]
ssh_only = false
style = "bg:#7449b8 fg:#c0caf5 bold"
format = "[ $hostname ]($style)"

[os]
disabled = false
style = "bg:#5e3d94 fg:#c0caf5 bold"

[os.symbols]
Arch = " 󰣇 "
Linux = " "

[directory]
style = "bg:#483170 fg:#c0caf5 bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = " "
style = "bg:#32254c fg:#c0caf5"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "bg:#32254c fg:#d4a031"
format = "[$all_status$ahead_behind ]($style)"

[fill]
symbol = " "

[cmd_duration]
min_time = 2_000
style = "fg:#8f97b0"
format = "[$duration ]($style)"

[character]
success_symbol = "[>>>](bold #3eb8a4)"
error_symbol = "[>>>](bold #e56b99)"

[python]
symbol = " "
style = "fg:#d4a031"
format = "[$symbol$version ]($style)"

[nodejs]
symbol = "󰎙 "
style = "fg:#05cb0d"
format = "[$symbol$version ]($style)"

[rust]
symbol = "󱘗 "
style = "fg:#d06a85"
format = "[$symbol$version ]($style)"

[golang]
symbol = "󰟓 "
style = "fg:#3eb8a4"
format = "[$symbol$version ]($style)"

[lua]
symbol = "󰢱 "
style = "fg:#6898d0"
format = "[$symbol$version ]($style)"
