polling_rate      = 1000

sleep_time        = 6
deep_sleep_time   = 12
key_response_time = 4

dpis = 400 600 700 800 1200 2400
# selected dpi 1-6
active_dpi = 3   

ripple_control = false
angle_snap     = false
