# =========================
# HYPRPAPER CONFIG 0.8.0+
# =========================

# Wallpaper para todos os monitores
wallpaper {
    monitor = 
    path = /home/vvaxis/Pictures/wallpapers/phoenix-space2.png
    fit_mode = cover
}

# Configurações opcionais
ipc = true
splash = false
